
version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: yarn dev
    ports:
      - "6211:6211"
    environment:
      NODE_ENV: development
